--DDL
/*
	테이블명 : product
	컬럼명 : id, name, maker, price
	데이터타입 : id와 price는 number. name과 maker는 varchar2(100)
	제약조건 : id는 primary key. name과 make는 not null. price는 default 0
*/

CREATE TABLE PRODUCT(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	MAKER VARCHAR2(100) NOT NULL,
	PRICE NUMBER DEFAULT 0
)

--DML
INSERT INTO PRODUCT(ID,NAME,MAKER,PRICE)VALUES(1,'불닭볶음면','삼양',1500);
INSERT INTO PRODUCT(ID,NAME,MAKER,PRICE)VALUES(2,'진라면','오뚜기',1100);
INSERT INTO PRODUCT(ID,NAME,MAKER,PRICE)VALUES(3,'테라','하이트진로',1800);
INSERT INTO PRODUCT(ID,NAME,MAKER,PRICE)VALUES(4,'참이슬후레쉬','하이트진로',1300);

SELECT * FROM PRODUCT;

--데이터베이스 함수 테스트
--수량 COUNT(*)
SELECT COUNT(*)
FROM PRODUCT;

--상품 최저가 구하기 (MIN)
SELECT MIN(PRICE)
FROM PRODUCT;

--상품 최고가 구하기 (MAX)
SELECT MAX(PRICE) AS 최고가
FROM PRODUCT;

--상품 평균가 구하기 (AVG)
SELECT AVG(PRICE) AS 평균가
FROM PRODUCT;

--정렬 : 오름차순 정렬 ASC, 내림차순 정렬 DESC
--PRICE기준으로 정렬-> ORDER BY!!
--ORDER BY -> DEFAULT는 오름차순(ASC)
SELECT NAME,PRICE
FROM PRODUCT
ORDER BY PRICE; 

SELECT NAME,PRICE
FROM PRODUCT
ORDER BY PRICE DESC; 

/*
 *  SELECT 컬럼명
 *  FROM 테이블명
 *  WHERE 조건절 AND 조건절
 * 	GROUP BY 컬럼명
 *  HAVING
 *  ORDER BY
 */

--MAKER가 하이트진로인 상품의 ID,NAME,PRICE를 조회하되, PRICE 내림차순으로 정렬
SELECT ID,NAME,PRICE
FROM PRODUCT
WHERE MAKER='하이트진로'
ORDER BY PRICE DESC;


--PRICE가 1300이상 1700이하인 상품의 NAME,PRICE를 조회. PRICE 오름차순
SELECT NAME,PRICE
FROM PRODUCT
WHERE PRICE>=1300 AND PRICE<=1700
--WHERE PRICE BETWEEN 1300 AND 1700
ORDER BY PRICE ASC;

--PRIMARY KEY(ID)로 검색해서 상품의 존재 유무 확인
SELECT COUNT(*)  --> PK : UNIQUE+NOTNULL
FROM PRODUCT
WHERE ID=2;

--COUNT -> 존재하지 않으면 0!! NULL이 아님
SELECT COUNT(*) 
FROM PRODUCT
WHERE ID=5;

--DISTINCT : MAKER의 종류를 조회. "중복없이"
SELECT DISTINCT MAKER
FROM PRODUCT;

--LIKE연산자 : 데이터의 일부가 포함되는 정보를 검색하는 연산자
--WHERE 컬럼명 LIKE '%키워드%'
-- % : 0개 이상의 문자
SELECT * FROM PRODUCT WHERE NAME LIKE '%면%';
SELECT * FROM PRODUCT WHERE NAME LIKE '%라%';
SELECT * FROM PRODUCT WHERE MAKER LIKE '%트진%';

--위 SQL들을 어플리케이션에서 적용 : 03-jdbc-product에서 구현





















